### DISCUSSION TITLE
Add Schema Store

### DISCUSSION THREAD

**Discussion by DrummyFloyd** [LazyVim/LazyVim#1905] [Q&A]
Hi wanted to know how can i add this 
`https://goauthentik.io/blueprints/schema.json`

to shcema store in Lazy vim for Yaml file =) ? 

in advance , thank you to you !

**Comment by DrummyFloyd** [comment]
meanwhile , i found a way to do it directly with LSP as "header of my yaml file"

my_file.yaml
```yaml
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Default - Password Recovery Flow
context:
  show_matched_user: true
  user_fields:
    - email
    - username
entries:
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  - model: authentik_stages_identification.identificationstage
    id: recovery-identification-stage
    identifiers:
      name: recovery-identification-stage
    attrs:
      user_fields: !Context user_fields
      show_matched_user: !Context show_matched_user
      sources:
        - 0
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

```
