### DISCUSSION TITLE
In-file declaration of schemas

### DISCUSSION THREAD

**Discussion by frantathefranta** [LazyVim/LazyVim#3185] [General]
Hi,
I'm coming back to neovim as an IDE of sorts because I need to do work in a remote terminal and it seems like the best option. I work with kubernetes and currently using Emacs, lots of my files have an in-file declaration of the schema I want to use. Example:
```yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
```
This doesn't seem possible in neovim yet and I'm wondering if it ever will be? I tried today to get it sort of working with [someone-stole-my-name/yaml-companion.nvim](https://github.com/someone-stole-my-name/yaml-companion.nvim) and [this guide](https://www.arthurkoziel.com/json-schemas-in-neovim/). But it works so-so and doesn't support custom CRDs. Another problem is that I use different schemas for the same CRD sometimes, which would be impossible to handle with just these tools. 

AFAIK VSCode also supports this in a way that's comparable to Emacs but I'm hesitant to use it. I'd like to continue using Emacs but it doesn't really seem to do that well in a remote environment (with TRAMP or using it in terminal mode). 

Does helix works with this method? I'm not at all familiar with it. Or am I just missing something obvious in my neovim settings?

Thanks for any suggestions!
