### DISCUSSION TITLE
[Issue] Strange font artifact in dashboard header

### DISCUSSION THREAD

**Discussion by pidgeon777** [LazyVim/LazyVim#3278] [Q&A]
There is a peculiar issue of font misalignment in `LazyVim` dashboard, as seen with `Neovide`:

![image](https://github.com/LazyVim/LazyVim/assets/13739892/a2454413-ab37-432e-8361-4b2721e462d0)

This issue also occurs without GUI (simply by running `nvim`):

![image](https://github.com/LazyVim/LazyVim/assets/13739892/fe2919ca-62d3-48ee-8225-7ee349723ad1)

I distinctly remember that there used to be no spacing between the rectangles that make up the `LazyVim` logo.

I have set `FiraCode Nerd Font Mono` as my **normal** font for Neovide:
 
 ```toml
 [font]
 normal = ["FiraCode Nerd Font Mono"]
 bold = ["FiraCode Nerd Font Mono"]
 italic = ["Cascadia Code"]
 bold_italic = ["Cascadia Code"]
 size = 10
 ```
 
On the other hand, Neovim's `set guifont` command returns `guifont=FiraCode Nerd Font Mono:h8,mini-file-icons:h12`.
