### DISCUSSION TITLE
Bug? There are some problems with using lazygit in lazyvim

### DISCUSSION THREAD

**Discussion by iamxiaojianzheng** [LazyVim/LazyVim#3682] [Q&A]
Toggle lazygit in lazyvim.

Unable to open the git file item to the current nvim using `e`. 

lazygit config.yml
```yml
os:
    editCommand: "nvim"
    editCommandTemplate: "{{editor}} --server $NVIM --remote-tab {{filename}}"
```
