### DISCUSSION TITLE
Toml changes in lazyvim is reverting back when I save it.

### DISCUSSION THREAD

**Discussion by harshv5094** [LazyVim/LazyVim#4002] [General]
I don't know it is a bug or not, So I'm posting it here. Whenever I'm trying to save my toml file changes, it automatically undo's all my work. I use alacritty so it's very unconvinient for me. I'm posting my lsp config file link [here](https://github.com/harshv5094/dotfiles-public/blob/main/.config/nvim/lua/plugins/lsp.lua) for someone to checkout.

**Comment by dpetka2001** [comment]
What do you mean it undoes your work? Give an example.

**Reply by harshv5094** [reply]
I'm explaining it through a code example 

```toml
# Initial Code before entering Insert Mode
foo = "bar"

# Changes done when I'm insert mode. Then I try to save it after leaving Insert Mode.
foo = "oof"

# Changes revert back to previous changes before entering Insert Mode.
foo = "bar"
```
