### DISCUSSION TITLE
How do I specify format options for ruff language server?

### DISCUSSION THREAD

**Discussion by skolj** [LazyVim/LazyVim#4560] [Q&A] [answered]
I'm currently using the following options to specify the formatting settings but LazyVim doesn't seem to obey them:
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      ruff = {
        init_options = {
          settings = {
            format = {
              ["quote-style"] = "single",
            },
          },
        },
      },
    },
  },
 }
```

The formatting works correctly when I include a `ruff.toml` in the project root with the following options:
```toml
[format]
# Like Black, use double quotes for strings.
quote-style = "single"
```
but I'd like to provide default settings. Could someone be so kind to help me fix this? Thanks!
