### DISCUSSION TITLE
How I can set indentation for `.toml` files?

### DISCUSSION THREAD

**Discussion by harshv5094** [LazyVim/LazyVim#5365] [General]
I love indentation in my `.toml` files
```toml
[basic]
 foo = true
 bar = 0
 [foo]
  bar = 1
```
I tried to search as to how I can configure my `conform.nvim`, but not found any solution. Could anyone help me?
