### DISCUSSION TITLE
Disable noice split on startup

### DISCUSSION THREAD

**Discussion by zeitchef** [LazyVim/LazyVim#6145] [Q&A]
New to LazyVim and I'm trying to figure out how to prevent this split (Noice showing `messages`) from opening when starting LazyVim. I've cleared all sessions and I can't understand why it's opening.
<img width="1266" alt="Screenshot 2025-06-02 at 16 26 58" src="https://github.com/user-attachments/assets/b2a0450b-22b3-41cd-8cc5-122113f37e2b" />
Any tips would be greatly appreciated! 🙏🏻

**Comment by dpetka2001** [comment]
This only opens up the first time you install Lazyvim. Not after that.

**Reply by zeitchef** [reply]
@dpetka2001 Unfortunately that's not the behavior I'm seeing. This is happening every time I start LazyVim.

**Reply by dpetka2001** [reply]
Then it has something to do with your OS. I've never seen this other than the first time Lazyvim got installed. Except if the treesitter parsers don't get installed correctly because you don't have necessary compiler in your OS and Lazyvim keeps trying installing them. 

You should run `:checkhealth` and if there are issues you should address them.

**Reply by zeitchef** [reply]
@dpetka2001 I appreciate your taking the time to help. I don't see anything here that would cause an issue like this, do you? It reports the parsers are installing just fine.

```
==============================================================================
auto-session:                                                               ✅

vim options ~
- ✅ OK vim.o.sessionoptions

Lazy.nvim settings ~
- ✅ OK Lazy.nvim support is enabled
- ✅ OK auto-session is not lazy loaded

Config ~
- ✅ OK {
    auto_restore_last_session = true,
    log_level = "error",
    suppressed_dirs = { "~/", "~/Documents", "~/Downloads" }
  }

General Info ~
- Session directory: /Users/scottvoyles/.local/share/lazyvim/sessions/
- Current session: /Users/scottvoyles/.dotfiles/lazyvim/.config/lazyvim
- Current session file: /Users/scottvoyles/.local/share/LazyVim/sessions/%2FUsers%2Fscottvoyles%2F%2Edotfiles%2Flazyvim%2F%2Econfig%2Flazyvim.vim

==============================================================================
blink.cmp:                                                                1 ⚠️

System ~
- ✅ OK curl is installed
- ✅ OK git is installed
- ✅ OK Your system is supported by pre-built binaries (aarch64-apple-darwin)
- ✅ OK blink_cmp_fuzzy lib is downloaded/built

Sources ~
- ⚠️ WARNING Some providers may show up as "disabled" but are enabled dynamically (i.e. cmdline)

Default sources ~
- snippets (blink.cmp.sources.snippets)
- lazydev (lazydev.integrations.blink)
- path (blink.cmp.sources.path)
- buffer (blink.cmp.sources.buffer)
- lsp (blink.cmp.sources.lsp)
- copilot (blink-cmp-copilot)

Disabled sources ~
- cmdline (blink.cmp.sources.cmdline)
- codecompanion (codecompanion.providers.completion.blink)
- omni (blink.cmp.sources.complete_func)

==============================================================================
codecompanion:                                                              ✅

- Neovim version: 0.11.2
- Log file: /Users/scottvoyles/.local/state/lazyvim/codecompanion.log

Dependencies: ~
- ✅ OK plenary.nvim installed
- ✅ OK nvim-treesitter installed

Tree-sitter parsers: ~
- ✅ OK markdown parser installed
- ✅ OK yaml parser installed

Libraries: ~
- ✅ OK curl installed
- ✅ OK base64 installed

==============================================================================
conform:                                                                  5 ⚠️

conform.nvim report ~
- Log file: /Users/scottvoyles/.local/state/lazyvim/conform.log
- ⚠️ WARNING fish_indent unavailable: Command 'fish_indent' not found
- ⚠️ WARNING markdown-toc unavailable: Condition failed
- ⚠️ WARNING markdownlint-cli2 unavailable: Condition failed
- ⚠️ WARNING prettier unavailable: Condition failed
- ⚠️ WARNING prettierd unavailable: Command 'prettierd' not found
- ✅ OK shfmt ready (sh)
- ✅ OK stylua ready (lua)
- ✅ OK trim_whitespace ready (*)

==============================================================================
fzf_lua:                                                                  3 ⚠️

fzf-lua [required] ~
- ✅ OK 'fzf' `0.62.0 (brew)`
- ✅ OK 'git' `git version 2.39.5 (Apple Git-154)`
- ✅ OK 'rg' `ripgrep 14.1.1`
- ✅ OK 'fd' `fd 10.2.0`

fzf-lua [optional] ~
- ✅ OK `nvim-web-devicons` found
- ✅ OK 'rg' `ripgrep 14.1.1`
- ✅ OK 'fd' `fd 10.2.0`
- ✅ OK 'bat' `bat 0.25.0`

fzf-lua [optional:media] ~
- ⚠️ WARNING 'viu' not found
- ⚠️ WARNING 'chafa' not found
- ⚠️ WARNING 'ueberzugpp' not found

fzf-lua [env] ~
- ✅ OK `FZF_DEFAULT_OPTS` is not set
- ✅ OK `FZF_DEFAULT_OPTS_FILE` is not set

==============================================================================
lazy:                                                                     2 ⚠️

lazy.nvim ~
- {lazy.nvim} version `11.17.1`
- ✅ OK {git} `version 2.39.5 (Apple Git-154)`
- ✅ OK no existing packages found by other package managers
- ✅ OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- ✅ OK no plugins require `luarocks`, so you can ignore any warnings below
- ✅ OK {luarocks} `/opt/homebrew/bin/luarocks 3.11.1`
- ⚠️ WARNING `lua` version `5.1` needed, but found `Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio`
- ⚠️ WARNING {lua5.1} or {lua} or {lua-5.1} version `5.1` not installed

==============================================================================
lazyvim:                                                                    ✅

LazyVim ~
- ✅ OK Using Neovim >= 0.9.0
- ✅ OK `git` is installed
- ✅ OK `rg` is installed
- ✅ OK `fd` is installed
- ✅ OK `lazygit` is installed
- ✅ OK `fzf` is installed
- ✅ OK `curl` is installed

==============================================================================
lspconfig:                                                                  ✅

- Skipped. This healthcheck is redundant with `:checkhealth vim.lsp`.

==============================================================================
mason:                                                                    5 ⚠️

mason.nvim ~
- ⚠️ WARNING mason.nvim version v1.11.0
  - ADVICE:
    - The latest version of mason.nvim is: v2.0.0
- ✅ OK PATH: prepend
- ✅ OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- ✅ OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- ✅ OK Registry `github.com/mason-org/mason-registry version: 2025-06-03-inborn-error` is installed.

mason.nvim [Core utils] ~
- ✅ OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP, with modifications by Apple Inc.`
- ✅ OK wget: `GNU Wget 1.25.0 built on darwin24.1.0.`
- ✅ OK curl: `curl 8.7.1 (x86_64-apple-darwin24.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.64.0`
- ✅ OK gzip: `Apple gzip 457.120.3`
- ✅ OK gtar: `tar (GNU tar) 1.35`
- ✅ OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)`
- ✅ OK sh: `Ok`

mason.nvim [Languages] ~
- ⚠️ WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- ⚠️ WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- ⚠️ WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- ✅ OK Ruby: `ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]`
- ✅ OK node: `v23.6.0`
- ✅ OK Go: `go version go1.24.3 darwin/arm64`
- ✅ OK luarocks: `/opt/homebrew/bin/luarocks 3.11.1`
- ⚠️ WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- ✅ OK python: `Python 3.11.11`
- ✅ OK java: `openjdk version "21.0.7" 2025-04-15`
- ✅ OK javac: `javac 21.0.7`
- ✅ OK RubyGem: `3.6.2`
- ✅ OK npm: `10.9.2`
- ✅ OK pip: `pip 25.0 from /Users/scottvoyles/.local/share/mise/installs/python/3.11.11/lib/python3.11/site-packages/pip (python 3.11)`
- ✅ OK python venv: `Ok`

mason.nvim [GitHub] ~
- ✅ OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Tue Jun  3 10:47:34 2025.

==============================================================================
noice:                                                                      ✅

noice.nvim ~
- ✅ OK *Neovim* >= 0.9.0
- ✅ OK You're using a GUI that should work ok
- ✅ OK *vim.go.lazyredraw* is not enabled
- ✅ OK `snacks.nvim` is installed
- ✅ OK {TreeSitter} `vim` parser is installed
- ✅ OK {TreeSitter} `regex` parser is installed
- ✅ OK {TreeSitter} `lua` parser is installed
- ✅ OK {TreeSitter} `bash` parser is installed
- ✅ OK {TreeSitter} `markdown` parser is installed
- ✅ OK {TreeSitter} `markdown_inline` parser is installed
- ✅ OK `vim.notify` is set to **Noice**
- ✅ OK `vim.lsp.buf.hover` is set to **Noice**
- ✅ OK `vim.lsp.buf.signature_help` is set to **Noice**
- ✅ OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- ✅ OK `vim.lsp.util.stylize_markdown` is set to **Noice**

==============================================================================
nvim-treesitter:                                                            ✅

Installation ~
- ✅ OK `tree-sitter` found 0.25.5 (parser generator, only needed for :TSInstallFromGrammar)
- ✅ OK `node` found v23.6.0 (only needed for :TSInstallFromGrammar)
- ✅ OK `git` executable found.
- ✅ OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 17.0.0 (clang-1700.0.13.5)
- ✅ OK Neovim was compiled with tree-sitter runtime ABI version 15 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "24.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 24.5.0: Tue Apr 22 19:53:27 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6041"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - printf              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
snacks:                                                             9 ⚠️  1 ❌

Snacks ~
- ✅ OK setup called

Snacks.bigfile ~
- ✅ OK setup {enabled}

Snacks.dashboard ~
- ⚠️ WARNING setup {disabled}

Snacks.explorer ~
- ⚠️ WARNING setup {disabled}

Snacks.image ~
- ⚠️ WARNING setup {disabled}
- ✅ OK 'kitty' `kitty 0.42.1 created by Kovid Goyal`
- ✅ OK 'ghostty' `Ghostty 1.1.3`
- ✅ OK 'magick' `Version: ImageMagick 7.1.1-47 Q16-HDRI aarch64 22763 https://imagemagick.org`
- ✅ OK 'convert' `WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"`
- ✅ OK `ghostty` detected and supported
- ✅ OK `ghostty` supports unicode placeholders
- ✅ OK Inline images are available
- ✅ OK `tmux` detected and supported
- ✅ OK Terminal Dimensions:
  - {size}: `3026` x `2738` pixels
  - {scale}: `2.13`
  - {cell}: `17` x `37` pixels
- ✅ OK Available Treesitter languages:
    `html`, `javascript`, `markdown_inline`, `markdown`, `tsx`
- ⚠️ WARNING Missing Treesitter languages:
    `css`, `latex`, `norg`, `scss`, `svelte`, `typst`, `vue`
- ⚠️ WARNING Image rendering in docs with missing treesitter parsers won't work
- ✅ OK 'gs' `10.05.1`
- ✅ OK PDF files are supported
- ❌ ERROR None of the tools found: 'tectonic', 'pdflatex'
- ⚠️ WARNING `tectonic` or `pdflatex` is required to render LaTeX math expressions
- ✅ OK 'mmdc' `11.4.2`
- ✅ OK Mermaid diagrams are supported
- ✅ OK your terminal supports the kitty graphics protocol

Snacks.input ~
- ✅ OK setup {enabled}
- ✅ OK `vim.ui.input` is set to `Snacks.input`

Snacks.lazygit ~
- ✅ OK {lazygit} installed

Snacks.notifier ~
- ✅ OK setup {enabled}
- ✅ OK is ready

Snacks.picker ~
- ⚠️ WARNING setup {disabled}
- ⚠️ WARNING `vim.ui.select` for `Snacks.picker` is not enabled
- ✅ OK Available Treesitter languages:
    `regex`
- ✅ OK 'git' `git version 2.39.5 (Apple Git-154)`
- ✅ OK 'rg' `ripgrep 14.1.1`
- ✅ OK `Snacks.picker.grep()` is available
- ✅ OK 'fd' `fd 10.2.0`
- ✅ OK `Snacks.picker.files()` is available
- ✅ OK `Snacks.picker.explorer()` is available
- ✅ OK `SQLite3` is available

Snacks.quickfile ~
- ✅ OK setup {enabled}

Snacks.scope ~
- ✅ OK setup {enabled}

Snacks.scroll ~
- ✅ OK setup {enabled}

Snacks.statuscolumn ~
- ⚠️ WARNING setup {disabled}
- ✅ OK is manually configured
  - `vim.o.statuscolumn = "%!v:lua.require'snacks.statuscolumn'.get()"`

Snacks.terminal ~
- ✅ OK shell configured
  - `vim.o.shell`: /opt/homebrew/bin/zsh
  - `parsed`: { "/opt/homebrew/bin/zsh" }

Snacks.toggle ~
- ✅ OK {which-key} is installed

Snacks.words ~
- ✅ OK setup {enabled}

==============================================================================
vim.deprecated:                                                             ✅

- ✅ OK No deprecated functions detected

==============================================================================
vim.health:                                                                 ✅

Configuration ~
- ✅ OK no issues found

Runtime ~
- ✅ OK $VIMRUNTIME: /opt/homebrew/Cellar/neovim/0.11.2/share/nvim/runtime

Performance ~
- ✅ OK Build type: Release

Remote Plugins ~
- ✅ OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $COLORTERM="truecolor"

tmux ~
- ✅ OK escape-time: 1
- ✅ OK focus-events: on
- $TERM: tmux-256color

External Tools ~
- ✅ OK ripgrep 14.1.1 (/opt/homebrew/bin/rg)

==============================================================================
vim.lsp:                                                                    ✅

- LSP log level : WARN
- Log path: /Users/scottvoyles/.local/state/lazyvim/lsp.log
- Log size: 8 KB

vim.lsp: Active Clients ~
- lua_ls (id: 1)
  - Version: 3.13.5
  - Root directory: ~/.dotfiles/lazyvim/.config/lazyvim
  - Command: { "lua-language-server" }
  - Settings: {
      Lua = {
        codeLens = {
          enable = true
        },
        completion = {
          callSnippet = "Replace"
        },
        doc = {
          privateName = { "^_" }
        },
        hint = {
          arrayIndex = "Disable",
          enable = true,
          paramName = "Disable",
          paramType = true,
          semicolon = "Disable",
          setType = false
        },
        workspace = {
          checkThirdParty = false
        }
      }
    }
  - Attached buffers: 5
- copilot (id: 2)
  - Version: 1.324.0
  - Root directory: ~/.dotfiles
  - Command: { "node", "/Users/scottvoyles/.local/share/lazyvim/lazy/copilot.lua/copilot/js/language-server.js", "--stdio" }
  - Settings: {
      telemetry = {
        telemetryLevel = "all"
      }
    }
  - Attached buffers: 5

vim.lsp: Enabled Configurations ~

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No buffers contain mixed position encodings

==============================================================================
vim.provider:                                                             3 ⚠️

Clipboard (optional) ~
- ✅ OK Clipboard tool found: pbcopy

Node.js provider (optional) ~
- Node.js: v23.6.0

- Nvim node.js host: /Users/scottvoyles/.local/share/mise/installs/node/23.6.0/lib/node_modules/neovim/bin/cli.js
- ✅ OK Latest "neovim" npm/yarn/pnpm package is installed: 5.3.0


Perl provider (optional) ~
- ⚠️ WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You can disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
- ⚠️ WARNING No usable perl executable found

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /Users/scottvoyles/.local/share/mise/installs/python/3.11.11/bin/python3
- Python version: 3.11.11
- pynvim version: 0.5.2
- ✅ OK Latest pynvim is installed.

Python virtualenv ~
- ✅ OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
- ⚠️ WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You can disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

==============================================================================
vim.treesitter:                                                             ✅

Treesitter features ~
- Treesitter ABI support: min 13, max 15
- WASM parser support: false

Treesitter parsers ~
- ✅ OK Parser: bash                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/bash.so
- ✅ OK Parser: c                    ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/c.so
- ✅ OK Parser: c                    ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/c.so
- ✅ OK Parser: diff                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/diff.so
- ✅ OK Parser: git_config           ABI: 13, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/git_config.so
- ✅ OK Parser: git_rebase           ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/git_rebase.so
- ✅ OK Parser: gitattributes        ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/gitattributes.so
- ✅ OK Parser: gitcommit            ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/gitcommit.so
- ✅ OK Parser: gitignore            ABI: 13, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/gitignore.so
- ✅ OK Parser: html                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/html.so
- ✅ OK Parser: javascript           ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/javascript.so
- ✅ OK Parser: jsdoc                ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/jsdoc.so
- ✅ OK Parser: json                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/json.so
- ✅ OK Parser: json5                ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/json5.so
- ✅ OK Parser: jsonc                ABI: 13, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/jsonc.so
- ✅ OK Parser: lua                  ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/lua.so
- ✅ OK Parser: lua                  ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/lua.so
- ✅ OK Parser: luadoc               ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/luadoc.so
- ✅ OK Parser: luap                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/luap.so
- ✅ OK Parser: markdown             ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/markdown.so
- ✅ OK Parser: markdown             ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/markdown.so
- ✅ OK Parser: markdown_inline      ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/markdown_inline.so
- ✅ OK Parser: markdown_inline      ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/markdown_inline.so
- ✅ OK Parser: printf               ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/printf.so
- ✅ OK Parser: python               ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/python.so
- ✅ OK Parser: query                ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/query.so
- ✅ OK Parser: query                ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/query.so
- ✅ OK Parser: regex                ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/regex.so
- ✅ OK Parser: toml                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/toml.so
- ✅ OK Parser: tsx                  ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/tsx.so
- ✅ OK Parser: typescript           ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/typescript.so
- ✅ OK Parser: vim                  ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/vim.so
- ✅ OK Parser: vim                  ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/vim.so
- ✅ OK Parser: vimdoc               ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/vimdoc.so
- ✅ OK Parser: vimdoc               ABI: 14, path: /opt/homebrew/Cellar/neovim/0.11.2/lib/nvim/parser/vimdoc.so
- ✅ OK Parser: xml                  ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/xml.so
- ✅ OK Parser: yaml                 ABI: 14, path: /Users/scottvoyles/.local/share/lazyvim/lazy/nvim-treesitter/parser/yaml.so

==============================================================================
which-key:                                                               11 ⚠️

- ✅ OK Most of these checks are for informational purposes only.
  WARNINGS should be treated as a warning, and don't necessarily indicate a problem with your config.
  Please |DON'T| report these warnings as an issue.

Checking your config ~
- ✅ OK |mini.icons| is installed
- ✅ OK |nvim-web-devicons| is installed

Checking for issues with your mappings ~
- ✅ OK No issues reported

checking for overlapping keymaps ~
- ⚠️ WARNING In mode `n`, <s> overlaps with <sj>, <sh>, <snv>, <snh>, <sl>, <sk>:
  - <s>: splits
  - <sj>: go to split below
  - <sh>: go to left split
  - <snv>: create new vertical split
  - <snh>: create new horizontal split
  - <sl>: go to right split
  - <sk>: go to split above
- ⚠️ WARNING In mode `n`, <<Space>q> overlaps with <<Space>qs>, <<Space>qq>, <<Space>qd>, <<Space>qS>, <<Space>ql>:
  - <<Space>q>: Quit
  - <<Space>qs>: Restore Session
  - <<Space>qq>: Quit All
  - <<Space>qd>: Don't Save Current Session
  - <<Space>qS>: Select Session
  - <<Space>ql>: Restore Last Session
- ⚠️ WARNING In mode `n`, <<Space><Space>> overlaps with <<Space><Space>q>, <<Space><Space>w>:
  - <<Space><Space>>: Find Files (Root Dir)
  - <<Space><Space>q>: Quit without saving
  - <<Space><Space>w>: Overwrite buffer
- ⚠️ WARNING In mode `n`, <<Space>l> overlaps with <<Space>ls>, <<Space>li>:
  - <<Space>ls>: open Lazy
  - <<Space>li>: see installed LSPs
- ⚠️ WARNING In mode `n`, <<Space>w> overlaps with <<Space>wm>, <<Space>wd>:
  - <<Space>w>: Save buffer
  - <<Space>wm>: Enable Zoom Mode
  - <<Space>wd>: Delete Window
- ⚠️ WARNING In mode `n`, <gc> overlaps with <gcc>, <gcO>, <gco>:
  - <gc>: Toggle comment
  - <gcc>: Toggle comment line
  - <gcO>: Add Comment Above
  - <gco>: Add Comment Below
- ⚠️ WARNING In mode `n`, <gr> overlaps with <gri>, <gra>, <grr>, <grn>:
  - <gr>: References
  - <gri>: vim.lsp.buf.implementation()
  - <gra>: vim.lsp.buf.code_action()
  - <grr>: vim.lsp.buf.references()
  - <grn>: vim.lsp.buf.rename()
- ⚠️ WARNING In mode `x`, <i> overlaps with <ii>, <il>, <in>:
  - <i>: inside
  - <ii>: indent
  - <il>: last
  - <in>: next
- ⚠️ WARNING In mode `x`, <a> overlaps with <ai>, <al>, <an>, <a%>:
  - <a>: around
  - <ai>: indent
  - <al>: last
  - <an>: next
- ⚠️ WARNING In mode `o`, <a> overlaps with <ai>, <al>, <an>:
  - <a>: around
  - <ai>: indent
  - <al>: last
  - <an>: next
- ⚠️ WARNING In mode `o`, <i> overlaps with <ii>, <il>, <in>:
  - <i>: inside
  - <ii>: indent
  - <il>: last
  - <in>: next
- ✅ OK Overlapping keymaps are only reported for informational purposes.
  This doesn't necessarily mean there is a problem with your config.

Checking for duplicate mappings ~
- ✅ OK No duplicate mappings found
```
