### ISSUE TITLE
bug: custom yaml tags erroring, trying to use cloudformation / SAM tags

### ISSUE THREAD

**Issue by partounian** [LazyVim/LazyVim#5789]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.4

### Operating system/version

macOS 15.3.1

### Describe the bug

Tried many variations of creating a file in `lua/plugins` that either calls the SchemaStore plugin or the nvim-lspconfig and the yamlls server settings for adding custom file matchers to the existing AWS schema jsons (since they don't cover the file extension we're using `*.tmpl.yaml`) and/or just adding custom tags without luck. They error in the lsp diagnostics and I can't figure it out for the life of me.

### Steps To Reproduce

1. Create the following yaml file named `template.yaml` to test

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template for VPC + VPN (split-tunnel aka internet access not through vpn)

Resources:
  # Launch VPC + Client VPN
  ApplicationVpcClientVpn:
    Type: AWS::Serverless::Application
    Condition: ShouldCreateVpc
    Properties:
      Location: vpc-client-vpn/vpc-client-vpn.tmpl.yaml
      Parameters:
        EnvironmentTagName: !Ref EnvironmentTagName
        EnvironmentTagColor: !Ref EnvironmentTagColor
        VpnServerCert: !FindInMap [VpnServerCert, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpnClientCert: !FindInMap [VpnClientCert, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpcCidrBlock: !FindInMap [VpcCidrBlock, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpcDomainIp: !FindInMap [VpcDomainIp, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpnCidrBlock: !FindInMap [VpnCidrBlock, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpnSAMLProviderArn: !FindInMap [VpnSAMLProviderArn, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
        VpnSelfServiceSAMLProviderArn: !FindInMap [VpnSelfServiceSAMLProviderArn, !Ref EnvironmentTagName, !Ref EnvironmentTagColor]
```

2. Populate lua/plugins/yaml.lua with the following, try some options
 
```lua
-- tried so many variations of these
return {
  "neovim/nvim-lspconfig",
  opts = {
    yamlls = {
      settings = {
        yaml = {
          customTags = {
            "!fn",
            "!And",
            "!If",
            "!Not",
            "!Equals",
            "!Or",
            "!FindInMap sequence",
            "!Base64",
            "!Cidr",
            "!Ref",
            "!Ref Scalar",
            "!Sub",
            "!GetAtt",
            "!GetAZs",
            "!ImportValue",
            "!Select",
            "!Split",
            "!Join sequence",
          },
        },
      },
    },
  },
}

-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     settings = {
--       yaml = {
--             schemas = {
--                 -- https://github.com/b0o/SchemaStore.nvim/blob/e03b50ce453b1ce9f6b7805239c52db604d740dc/lua/schemastore/catalog.lua#L2189-L2199
--                 {
--                   description = "AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment",
--                   fileMatch = {
--                     "*.tmpl.yaml",
--                     "*.cf.json",
--                     "*.cf.yml",
--                     "*.cf.yaml",
--                     "cloudformation.json",
--                     "cloudformation.yml",
--                     "cloudformation.yaml",
--                   },
--                   name = "AWS CloudFormation",
--                   url = "https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json",
--                 },
--                 {
--                   description = "The AWS Serverless Application Model (AWS SAM, previously known as Project Flourish) extends AWS CloudFormation to provide a simplified way of defining the Amazon API Gateway APIs, AWS Lambda functions, and Amazon DynamoDB tables needed by your serverless application",
--                   fileMatch = {
--                     "*.tmpl.yaml",
--                     "template.yaml",
--                     "serverless.template",
--                     "*.sam.json",
--                     "*.sam.yml",
--                     "*.sam.yaml",
--                     "sam.json",
--                     "sam.yml",
--                     "sam.yaml",
--                   },
--                   name = "AWS CloudFormation Serverless Application Model (SAM)",
--                   url = "https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json",
--                 },
--             },
--         customTags = {
--           "!fn",
--           "!And",
--           "!If",
--           "!Not",
--           "!Equals",
--           "!Or",
--           "!FindInMap sequence",
--           "!Base64",
--           "!Cidr",
--           "!Ref",
--           "!Ref Scalar",
--           "!Sub",
--           "!GetAtt",
--           "!GetAZs",
--           "!ImportValue",
--           "!Select",
--           "!Split",
--           "!Join sequence",
--         },
--       },
--     },
--   },
-- }

-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       yamlls = {
--         settings = {
--           yaml = {
--             schemas = {
--               extra = {
--                 -- https://github.com/b0o/SchemaStore.nvim/blob/e03b50ce453b1ce9f6b7805239c52db604d740dc/lua/schemastore/catalog.lua#L2189-L2199
--                 {
--                   description = "AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment",
--                   fileMatch = {
--                     "*.tmpl.yaml",
--                     "*.cf.json",
--                     "*.cf.yml",
--                     "*.cf.yaml",
--                     "cloudformation.json",
--                     "cloudformation.yml",
--                     "cloudformation.yaml",
--                   },
--                   name = "AWS CloudFormation",
--                   url = "https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json",
--                 },
--                 {
--                   description = "The AWS Serverless Application Model (AWS SAM, previously known as Project Flourish) extends AWS CloudFormation to provide a simplified way of defining the Amazon API Gateway APIs, AWS Lambda functions, and Amazon DynamoDB tables needed by your serverless application",
--                   fileMatch = {
--                     "*.tmpl.yaml",
--                     "template.yaml",
--                     "serverless.template",
--                     "*.sam.json",
--                     "*.sam.yml",
--                     "*.sam.yaml",
--                     "sam.json",
--                     "sam.yml",
--                     "sam.yaml",
--                   },
--                   name = "AWS CloudFormation Serverless Application Model (SAM)",
--                   url = "https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json",
--                 },
--               },
--             },
--           },
--         },
--       },
--     },
--   },
-- }

-- return {
--   "b0o/SchemaStore.nvim",
--   opts = {
--     json = {
--       schemas = {
--         extra = {
--           -- https://github.com/b0o/SchemaStore.nvim/blob/e03b50ce453b1ce9f6b7805239c52db604d740dc/lua/schemastore/catalog.lua#L2189-L2199
--           {
--             description = "AWS CloudFormation provides a common language for you to describe and provision all the infrastructure resources in your cloud environment",
--             fileMatch = {
--               "*.tmpl.yml",
--               "*.cf.json",
--               "*.cf.yml",
--               "*.cf.yaml",
--               "cloudformation.json",
--               "cloudformation.yml",
--               "cloudformation.yaml",
--             },
--             name = "AWS CloudFormation",
--             url = "https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json",
--           },
--           {
--             description = "The AWS Serverless Application Model (AWS SAM, previously known as Project Flourish) extends AWS CloudFormation to provide a simplified way of defining the Amazon API Gateway APIs, AWS Lambda functions, and Amazon DynamoDB tables needed by your serverless application",
--             fileMatch = {
--               "*.tmpl.yml",
--               "template.yaml",
--               "serverless.template",
--               "*.sam.json",
--               "*.sam.yml",
--               "*.sam.yaml",
--               "sam.json",
--               "sam.yml",
--               "sam.yaml",
--             },
--             name = "AWS CloudFormation Serverless Application Model (SAM)",
--             url = "https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json",
--           },
--         },
--       },
--     },
--   },
-- }
```

### Expected Behavior

No yaml errors 

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- enable yaml language support from LazyExtras
  },
})
```
